export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS= 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const GRAB_USERS_BEGIN = 'GRAB_USERS_BEGIN'
export const GRAB_USERS_SUCCESS = 'GRAB_USERS_SUCCESS'
export const GRAB_USERS_ERROR = 'GRAB_USERS_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_WORK_BEGIN = 'CREATE_WORK_BEGIN'
export const CREATE_WORK_SUCCESS = 'CREATE_WORK_SUCCESS'
export const CREATE_WORK_ERROR = 'CREATE_WORK_ERROR'

export const GET_WORKS_BEGIN = 'GET_WORKS_BEGIN'
export const GET_WORKS_SUCCESS = 'GET_WORKS_SUCCESS'

export const GET_WORK_BEGIN = 'GET_WORK_BEGIN'
export const GET_WORK_SUCCESS = 'GET_WORK_SUCCESS'

export const SET_EDIT_WORK = 'SET_EDIT_WORK'

export const EDIT_WORK_BEGIN = 'EDIT_WORK_BEGIN'
export const EDIT_WORK_SUCCESS = 'EDIT_WORK_SUCCESS'
export const EDIT_WORK_ERROR = 'EDIT_WORK_ERROR'

export const DELETE_WORK_BEGIN = 'DELETE_WORK_BEGIN'

export const GET_CONTRIBUTIONS_BEGIN = 'GET_CONTRIBUTIONS_BEGIN'
export const GET_CONTRIBUTIONS_SUCCESS = 'GET_CONTRIBUTIONS_SUCCESS'

export const CREATE_CONTRIBUTION_BEGIN = 'CREATE_CONTRIBUTION_BEGIN'
export const CREATE_CONTRIBUTION_SUCCESS = 'CREATE_CONTRIBUTION_SUCCESS'
export const CREATE_CONTRIBUTION_ERROR = 'CREATE_CONTRIBUTION_ERROR'